# Generated by Django 5.2.1 on 2025-06-20 07:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Unnamed Type', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargoListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cargo_type', models.CharField(choices=[('general', 'General Goods'), ('perishable', 'Perishable Goods'), ('fragile', 'Fragile Items'), ('machinery', 'Machinery/Equipment'), ('construction', 'Construction Materials'), ('furniture', 'Furniture'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the cargo', max_length=500)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weight', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('volume', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Volume', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated value of cargo', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pickup_location', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('pickup_date', models.DateField(default=None, help_text='Date when cargo should be picked up', null=True)),
                ('delivery_date', models.DateField(default=None, help_text='Date when cargo should be delivered', null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Budget for the cargo transport', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preferred_payment', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card Payment')], default='CASH', max_length=20)),
                ('additional_requirements', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cargo_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_photos', to='cargo.cargolisting')),
            ],
        ),
        migrations.AddIndex(
            model_name='cargolisting',
            index=models.Index(fields=['status', 'created_at'], name='cargo_cargo_status_f2b471_idx'),
        ),
        migrations.AddIndex(
            model_name='cargolisting',
            index=models.Index(fields=['cargo_type', 'status'], name='cargo_cargo_cargo_t_bc404b_idx'),
        ),
        migrations.AddIndex(
            model_name='cargolisting',
            index=models.Index(fields=['pickup_location'], name='cargo_cargo_pickup__463681_idx'),
        ),
        migrations.AddIndex(
            model_name='cargolisting',
            index=models.Index(fields=['delivery_location'], name='cargo_cargo_deliver_13d861_idx'),
        ),
        migrations.AddIndex(
            model_name='cargolisting',
            index=models.Index(fields=['pickup_date'], name='cargo_cargo_pickup__d14300_idx'),
        ),
    ]
