# Generated by Django 5.2.1 on 2025-06-20 07:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, help_text='Bid amount in KSh', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('estimated_delivery_time', models.CharField(choices=[('same-day', 'Same Day'), ('next-day', 'Next Day'), ('2-3-days', '2-3 Days'), ('4-7-days', '4-7 Days'), ('custom', 'Custom'), ('unknown', 'Unknown')], help_text='How long will delivery take?', max_length=20)),
                ('custom_delivery_time', models.CharField(blank=True, help_text='Specify custom delivery timeframe', max_length=100, null=True)),
                ('message_to_shipper', models.TextField(blank=True, help_text='Include any conditions, questions, or details about your service')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this bid expires (optional)', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When shipper responded to this bid', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('shipper_notes', models.TextField(blank=True, help_text='Notes from shipper about this bid')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to=settings.AUTH_USER_MODEL)),
                ('cargo_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='cargo.cargolisting')),
            ],
            options={
                'db_table': 'freight_bids',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BidNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_bid', 'New Bid Received'), ('bid_accepted', 'Bid Accepted'), ('bid_rejected', 'Bid Rejected'), ('bid_withdrawn', 'Bid Withdrawn'), ('bid_expiring', 'Bid Expiring Soon')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bids.bid')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'freight_bid_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BidStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_bids_submitted', models.PositiveIntegerField(default=0)),
                ('bids_accepted', models.PositiveIntegerField(default=0)),
                ('bids_rejected', models.PositiveIntegerField(default=0)),
                ('average_bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_listings_posted', models.PositiveIntegerField(default=0)),
                ('total_bids_received', models.PositiveIntegerField(default=0)),
                ('average_bids_per_listing', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'freight_bid_statistics',
            },
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['cargo_listing', 'status'], name='freight_bid_cargo_l_8db4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder', 'status'], name='freight_bid_bidder__2a34e5_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['submitted_at', 'status'], name='freight_bid_submitt_b559ca_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bid_amount'], name='freight_bid_bid_amo_4bf590_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['estimated_delivery_time'], name='freight_bid_estimat_f896b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('cargo_listing', 'bidder')},
        ),
        migrations.AddIndex(
            model_name='bidnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='freight_bid_recipie_30f14f_idx'),
        ),
        migrations.AddIndex(
            model_name='bidnotification',
            index=models.Index(fields=['notification_type', 'sent_at'], name='freight_bid_notific_32deab_idx'),
        ),
    ]
